# Generated by Django 2.1.4 on 2018-12-12 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluidol_index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
