# Generated by Django 2.1.4 on 2018-12-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluidol_index', '0002_remove_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='temp'),
            preserve_default=False,
        ),
    ]
