# Generated by Django 2.1.4 on 2018-12-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluidol_index', '0003_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='temp description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
