# Generated by Django 2.1.4 on 2018-12-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluidol_index', '0005_auto_20181213_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_applications',
            field=models.ManyToManyField(blank=True, to='fluidol_index.Product_applications'),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_benefits',
            field=models.ManyToManyField(blank=True, to='fluidol_index.Product_benefits'),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_features',
            field=models.ManyToManyField(blank=True, to='fluidol_index.Product_features'),
        ),
    ]
